{
    'name': 'Insurance Management ',
    'version': '13.0.1.0.0',
    'category': 'Generic Modules/Others',
    'description': '****Insurance Management & Operations***',
    'summary': '****Insurance Management***',
    'author': 'Odoo Mates',
    'maintainer': 'Odoo Mates',
    'website': 'http://odoomates.tech',
    'support': 'odoomates@gmail.com',
    'license': 'LGPL-3',
    'depends': [ 'base', 'account' ],
    'data': [
        'views/insurance_details.xml',
        'views/policy_management.xml', 
        'views/insurance_management.xml',
        'security/ir.model.access.csv',  
    ],
    'images': ['static/description/banner.png'],
    'demo': [],
    'test': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
